export const categories = [
  {
    id: 1,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 2,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Techology",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 3,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "History",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 4,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Trading",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 5,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Traval",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 6,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 7,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 8,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 9,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 10,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 11,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 12,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 13,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 14,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
  {
    id: 15,
    image: "./images/homeimgs/catpolitical.jpg",
    bigtitle: "Political",
    title: "How to travel Bagan? What should I do?",
    para: "It is a long established fact that a reader will be distracte by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-lessormal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for'lorem ipsum' will uncover many web sites still in their infancy.",
  },
];
